apiVersion: apps/v1
kind: Deployment
metadata:
  name: probe-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: probe-test
  template:
    metadata:
      labels:
        app: probe-test
    spec:
      containers:
        - name: k8s-app-demo
          image: ghcr.io/diogoguedes11/k8s-app-demo:latest
          ports:
            - containerPort: 8080 # Changed from 80 to 8080
          livenessProbe:
            httpGet:
              path: /healthz # Changed from /health to /healthz
              port: 8080 # Changed from 80 to 8080
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /readiness # Changed from /ready to /readiness
              port: 8080 # Changed from 80 to 8080
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: probe-test-service
spec:
  selector:
    app: probe-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
